name: CI Build

on:
  push:
    branches: [ "testnet3_patched" ]
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  build_pool:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/testnet3_patched
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          file: ./docker/Dockerfile
          push: true
          target: base
          tags: ghcr.io/mechanizm/aleo_miner:latest
          cache-from: type=registry,ref=ghcr.io/mechanizm/aleo_miner:buildcache
          cache-to: type=registry,ref=ghcr.io/mechanizm/aleo_miner:buildcache,mode=max
